# Generated by Django 5.0.3 on 2024-04-29 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Middle_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=2)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Additional_Info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_License', models.CharField(max_length=20)),
                ('Driver_License_State', models.CharField(max_length=2)),
                ('Driver_License_Date_Issuance', models.DateField()),
                ('Driver_License_Date_Expiration', models.DateField(blank=True, null=True)),
                ('Driver_License_Class', models.CharField(blank=True, max_length=4, null=True)),
                ('Driver_License_Restrictions', models.CharField(blank=True, max_length=4, null=True)),
                ('Driver_License_Endorsements', models.CharField(blank=True, max_length=4, null=True)),
                ('License_Photo_Front', models.ImageField(blank=True, null=True, upload_to='license_photos/')),
                ('License_Photo_Back', models.ImageField(blank=True, null=True, upload_to='license_photos/')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
        ),
    ]
