# Generated by Django 5.0.3 on 2024-04-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_address_alter_driver_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='Date_of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
