# Generated by Django 5.0.3 on 2024-05-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0004_alter_driver_date_of_birth'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dispatch_creation', models.DateTimeField(auto_now_add=True)),
                ('date_dispatch_last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('pickup_date_start', models.DateField()),
                ('pickup_date_end', models.DateField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_date_start', models.DateField()),
                ('dropoff_date_end', models.DateField()),
                ('dropoff_location', models.CharField(max_length=255)),
                ('load_type', models.CharField(max_length=255)),
                ('load_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_hazmat', models.BooleanField(default=False)),
                ('is_team_driving', models.BooleanField(default=False)),
                ('is_expedited', models.BooleanField(default=False)),
                ('is_underweightlimit', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='vehicles.vehicle')),
            ],
        ),
    ]
