# Generated by Django 5.0.3 on 2024-04-18 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_vehiclefuelrecord_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclefuelrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='core.vehicle'),
        ),
    ]
